### ISSUE TITLE
Great idea, but need explanation of files

### ISSUE THREAD

**Issue by pcgeek86** [fernandojunior/python-boilerplate-module#1]
This project is a great idea, but I think you should include an explanation of what the purpose of each file is. Newbies will find the structure helpful, but also need to understand why each file exists, and what purpose it serves in the software development pipeline.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by fernandojunior** [comment]
Nice. I'll do this. Ty.
